const BLUE_COLOR = "#000062"; 
const WHITE_COLOR = "#FFFFFF";
const GREY_COLOR = "#C7C7C7";
const TAB_NAME_HISTORICAL_HOLDINGS = 'Holdings';
const TAB_NAME_TRANSCATIONS = 'Transactions';
const APPROXIMATE_ZERO = 0.00000001;

export {
    BLUE_COLOR, WHITE_COLOR, GREY_COLOR, TAB_NAME_TRANSCATIONS, TAB_NAME_HISTORICAL_HOLDINGS, APPROXIMATE_ZERO
};