const BLUE_COLOR = "#000062"; 
const WHITE_COLOR = "#FFFFFF";
const TAB_NAME_HISTORICAL_HOLDINGS = 'Holdings';
const TAB_NAME_TRANSCATIONS = 'Transactions';

export {
    BLUE_COLOR, WHITE_COLOR, TAB_NAME_TRANSCATIONS, TAB_NAME_HISTORICAL_HOLDINGS
};